### ISSUE TITLE
How should I build Equalizer on Mac OS 10.11?Is the latest Release compatible with this version?

### ISSUE THREAD

**Issue by wangzilu** [Eyescale/Equalizer#523]

**Comment by eile** [comment]
If you have Macports, ```cmake -DINSTALL_PACKAGES=1 .. ``` should configure and install the necessary dependencies. Afaik @tribal-tec did build on 10.11.

**Comment by wangzilu** [comment]
Danke schoen！

**Comment by wangzilu** [comment]
I build equalizer with cmake -DINSTALL_PACKAGES=1 .. and it shows 
Configured Equalizer [2f295b5] with Boost Collage GLStats hwsd Lunchbox OpenCV OpenGL Pression vmmlib WITHOUT Deflect hwloc MAGELLAN OpenSceneGraph Qt5Core Qt5Gui Qt5Widgets VRPN X11 CUDA GLEW_MX hwloc

and then I make ,

it gives a error,

1 error generated.
make[2]: *** [Lunchbox/lunchbox/CMakeFiles/Lunchbox.dir/thread.cpp.o] Error 1
make[1]: *** [Lunchbox/lunchbox/CMakeFiles/Lunchbox.dir/all] Error 2
make: *** [all] Error 2

**Comment by wangzilu** [comment]
/Users/oukoro/Downloads/Equalizer/Lunchbox/lunchbox/thread.cpp:139:7: error: 
      expected unqualified-id
    ::sigfillset( &sa.sa_mask );
      ^
/usr/include/signal.h:126:26: note: expanded from macro 'sigfillset'
#define sigfillset(set)         (*(set) = ~(sigset_t)0, 0)

**Comment by wangzilu** [comment]
I removed :: and it worked...

**Comment by wangzilu** [comment]
Not configured Deflect: Required LibJpegTurbo not found
-- Configured Equalizer [2f295b5] with Boost Collage GLStats hwsd Lunchbox OpenCV OpenGL Pression vmmlib WITHOUT Deflect hwloc MAGELLAN OpenSceneGraph Qt5Core Qt5Gui Qt5Widgets VRPN X11 CUDA GLEW_MX hwloc
-- Configured GLEW_MX_Equalizer [1.9.0]
 I installed QT and how should I configured it and X11
