### ISSUE TITLE
Compile error on Ubuntu 14.04: libusb.h not found

### ISSUE THREAD

**Issue by lguyot** [Eyescale/Equalizer#354]
Few moments after typing

```
make Equalizer
```

I get the following compile error:

```
[ 11%] Building CXX object eq/client/CMakeFiles/Equalizer.dir/observer.cpp.o
In file included from /home/lguyot/develop/Buildyard/src/Equalizer/eq/client/observer.cpp:34:0:
/home/lguyot/develop/Buildyard/Build/install/include/vrpn_Tracker.h:176:20: fatal error: libusb.h: No such file or directory
```

(Note: /usr/include/libusb-1.0/libusb.h exists)

**Comment by RubenGarcia** [comment]
vrpn build was also broken in windows, I had to build vrpn outside of equalizer. The current git version of vrpn seems to work on its own.
