### ISSUE TITLE
EqualizerServer does not compile on ubuntu 14.04 (possibly others as well)

### ISSUE THREAD

**Issue by RubenGarcia** [Eyescale/Equalizer#514]
Cloning new Equalizer; mkdir build; cd build; cmake ..; make
When running make:

[ 15%] Building CXX object eq/server/CMakeFiles/EqualizerServer.dir/config/resources.cpp.o
/home/rgarcia/lrz/equalizer/Equalizer/eq/server/config/resources.cpp: In static member function ‘static bool eq::server::config::Resources::discover(eq::server::ServerPtr, eq::server::Config, const string&, const eq::fabric::ConfigParams&)’:
/home/rgarcia/lrz/equalizer/Equalizer/eq/server/config/resources.cpp:328:34: error: ‘FLAG_VNC’ is not a member of ‘hwsd::GPUInfo’
hwsd::GPUInfo::FLAG_VNC )) ==
^
make[2]: ** [eq/server/CMakeFiles/EqualizerServer.dir/config/resources.cpp.o] Error 1
make[1]: *** [eq/server/CMakeFiles/EqualizerServer.dir/all] Error 2

**Comment by RubenGarcia** [comment]
Caused by an old installed version of hwsd in /usr
Wishlist: It may make sense to test if the hwsd version is too old and avoid using it if so.
Closing.
